alertmanager:

  config:

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 10s
      receiver: 'email-notifications'
   
   

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'critical'
        equal: ['alertname', 'dev', 'instance']
